# Generated by Django 5.2 on 2025-05-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_at_purchase',
            new_name='price',
        ),
    ]
