# Generated by Django 5.2 on 2025-05-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('-id',), 'verbose_name_plural': 'ProductCategory'},
        ),
    ]
